name: CI

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main ]

jobs:
  flutter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Flutter version
        run: flutter --version
      - name: Get dependencies
        run: |
          cd maathai_llamma
          flutter pub get
      - name: Analyze
        run: |
          cd maathai_llamma
          dart analyze .
      - name: Test
        run: |
          cd maathai_llamma
          flutter test --no-pub
